version: '3'
services:
    manager-nginx:
        build:
            context: ./framework/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./framework:/app
        depends_on:
            - manager-php-fpm
        ports:
            - "8080:80"
    manager-php-fpm:
        build:
            context: ./framework/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./framework:/app
    manager-php-cli:
        build:
            context: ./framework/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./framework:/app
            - composer:/root/.composer/cache
    manager-postgres:
        image: postgres:11.2-alpine
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"

volumes:
    manager-postgres:
    composer: